channels:
  feishu:
    app_id: ''
    app_secret: ''
    auto_start: true
    enabled: true
    whitelist_users: []
  qq:
    app_id: ''
    app_secret:
    auto_start: true
    enabled: true
    intents: 1107296256
  telegram:
    auto_start: true
    bot_token: ''
    enabled: true
    whitelist_user_ids: []
    whitelist_usernames: []
  weixin:
    auto_start: true
    bot_agent: Cellium Agent
    enabled: true
    state_dir: data/weixin
