# -*- coding: utf-8 -*-
"""
Cellium TUI 主题
"""
from textual.theme import Theme

LIGHT_THEME = Theme(
    name="cellium-light",
    dark=False,
    primary="#1a73e8",
    secondary="#5f6368",
    accent="#1a73e8",
    warning="#f9ab00",
    error="#d93025",
    success="#188038",
    foreground="#202124",
    background="#f5f5f5",
    surface="#ffffff",
    panel="#f8f9fa",
    variables={
        "border-primary": "#e0e0e0",
        "border-secondary": "#dadce0",
        "text-secondary": "#5f6368",
        "text-tertiary": "#9aa0a6",
        "text-muted": "#6b7280",
        "bg-hover": "#f1f3f4",
        "bg-active": "#e8f0fe",
        "msg-user-bg": "#e8f0fe",
        "msg-user-text": "#202124",
        "msg-assistant-bg": "#ffffff",
        "msg-system-bg": "#fef3e8",
        "msg-system-text": "#b06000",
        "code-bg": "#f6f8fa",
        "input-bg": "#ffffff",
        "scrollbar-thumb": "#c1c1c1",
        "button-focus-text-style": "bold",
        "markdown-h1-color": "#1a73e8",
        "markdown-h2-color": "#1a73e8",
        "markdown-h3-color": "#1a73e8",
        "markdown-h4-color": "#1a73e8",
        "markdown-h5-color": "#1a73e8",
        "markdown-h6-color": "#1a73e8",
        "markdown-h1-background": "transparent",
        "markdown-h2-background": "transparent",
        "markdown-h3-background": "transparent",
        "markdown-h4-background": "transparent",
        "markdown-h5-background": "transparent",
        "markdown-h6-background": "transparent",
        "markdown-h1-text-style": "bold",
        "markdown-h2-text-style": "bold",
        "markdown-h3-text-style": "bold",
        "markdown-h4-text-style": "bold",
        "markdown-h5-text-style": "bold",
        "markdown-h6-text-style": "bold",
    },
)

DARK_THEME = Theme(
    name="cellium-dark",
    dark=True,
    primary="#58a6ff",
    secondary="#8b949e",
    accent="#58a6ff",
    warning="#d29922",
    error="#f85149",
    success="#3fb950",
    foreground="#e6edf3",
    background="#0d1117",
    surface="#161b22",
    panel="#21262d",
    variables={
        "border-primary": "#30363d",
        "border-secondary": "#21262d",
        "text-secondary": "#8b949e",
        "text-tertiary": "#6e7681",
        "text-muted": "#8b949e",
        "bg-hover": "#30363d",
        "bg-active": "rgba(56,139,253,0.15)",
        "msg-user-bg": "#238636",
        "msg-user-text": "#ffffff",
        "msg-assistant-bg": "#161b22",
        "msg-system-bg": "#341a00",
        "msg-system-text": "#d29922",
        "code-bg": "#0d1117",
        "input-bg": "#161b22",
        "scrollbar-thumb": "#30363d",
        "button-focus-text-style": "bold",
        "markdown-h1-color": "#58a6ff",
        "markdown-h2-color": "#58a6ff",
        "markdown-h3-color": "#58a6ff",
        "markdown-h4-color": "#58a6ff",
        "markdown-h5-color": "#58a6ff",
        "markdown-h6-color": "#58a6ff",
        "markdown-h1-background": "transparent",
        "markdown-h2-background": "transparent",
        "markdown-h3-background": "transparent",
        "markdown-h4-background": "transparent",
        "markdown-h5-background": "transparent",
        "markdown-h6-background": "transparent",
        "markdown-h1-text-style": "bold",
        "markdown-h2-text-style": "bold",
        "markdown-h3-text-style": "bold",
        "markdown-h4-text-style": "bold",
        "markdown-h5-text-style": "bold",
        "markdown-h6-text-style": "bold",
    },
)


def register_cellium_themes(app):
    app.register_theme(LIGHT_THEME)
    app.register_theme(DARK_THEME)
